FROM ubuntu:26.04

COPY --from=lamka02sk/picturium-base:8.18.4 /usr/local/lib /usr/local/lib
COPY --from=lamka02sk/picturium-base:8.18.4 /usr/bin/gs /usr/bin/gs
COPY --from=lamka02sk/picturium-base:8.18.4 /usr/local/bin/vips /usr/local/bin/vips
COPY --from=lamka02sk/picturium-base:8.18.4 /lib/x86_64-linux-gnu /lib/x86_64-linux-gnu
COPY --from=lamka02sk/picturium-base:8.18.4 /lib/aarch64-linux-gnu /lib/aarch64-linux-gnu
COPY --from=lamka02sk/picturium-base:8.18.4 /usr/lib/libreoffice /usr/lib/libreoffice
COPY --from=lamka02sk/picturium-base:8.18.4 /usr/share/libreoffice /usr/share/libreoffice
COPY --from=lamka02sk/picturium-base:8.18.4 /usr/share/liblangtag /usr/share/liblangtag
COPY --from=lamka02sk/picturium-base:8.18.4 /usr/share/color /usr/share/color
COPY --from=lamka02sk/picturium-base:8.18.4 /usr/share/ghostscript /usr/share/ghostscript
COPY --from=lamka02sk/picturium-base:8.18.4 /usr/share/poppler /usr/share/poppler
COPY --from=lamka02sk/picturium-base:8.18.4 /usr/share/mime /usr/share/mime
COPY --from=lamka02sk/picturium-base:8.18.4 /etc /etc

RUN apt update -y && apt install -y curl gcc && apt install -y --no-install-recommends ffmpeg && apt autoremove && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Rust
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/usr/lib/libreoffice/program:/root/.cargo/bin:${PATH}"
RUN cargo install cargo-watch

RUN mkdir /root/picturium && ldconfig

WORKDIR /root/picturium
ENV RUSTFLAGS="-C linker-features=-lld"
CMD ["cargo", "watch", "-d", "2", "-w", "/root/picturium/src", "-x", "run"]
